development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: ENV['REDISCLOUD_URL']

# CREATE A REDIS INSTANCE AND PUT IN A REDISTOGO:..........
# WATCH TUTORIAL ABOUT This
