# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2516a27e1746fd9b86a73675392a92f79d524f5f36a64e1676ef66626d4a15677b61b5b22554be37f7de4857fcfcd2b298edfb340c0d44132bb54ee098ad3f4

test:
  secret_key_base: b11b3b826fe5e09193f12fd8ac14a76e00bc694ad52e8c971e875f71767ca1dd2e4ae764490b6933e94913216d92ab55077afd8b6d4b4ee632025f769087748f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
